stages:
  - build

build_image_prod:
  stage: build
  tags:
    - sleep_ai
  script:
    - cd /sleeptery/Sleeptery-AI-PROD/
    - docker compose down
    - rsync -zvrh --delete --exclude='appqdrant_storage' $CI_PROJECT_DIR/* /sleeptery/Sleeptery-AI-PROD/
    - docker compose up --build -d
    - docker ps
  rules:
    - if: '$CI_COMMIT_BRANCH == "prod" && $CI_PIPELINE_SOURCE == "push"'

build_image_dev:
  stage: build
  tags:
    - sleep_ai
  script:
    - cd /sleeptery/Sleeptery-AI-DEV/
    - docker compose down
    - rsync -zvrh --delete --exclude='appqdrant_storage' $CI_PROJECT_DIR/* /sleeptery/Sleeptery-AI-DEV/
    - docker compose up --build -d
    - docker ps
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" && $CI_PIPELINE_SOURCE == "push"'
