stages:
  - build


build_image_prod:
  stage: build
  tags:
    - sleep_ai
  script:
    - rsync -zvrh ./* /sleeptery/Sleeptery-AI-PROD/
    - cd /sleeptery/Sleeptery-AI-PROD/
    # - docker compose down
    - docker compose up --build -d
    - docker ps
    - docker logs sleep_ai_app
    - docker logs consumer_prod
    - docker logs consumer_dev
  rules:
    - if: '$CI_COMMIT_BRANCH == "prod" && $CI_PIPELINE_SOURCE == "push"'

  
  build_image_dev:
  stage: build
  tags:
    - sleep_ai
  script:
    - rsync -zvrh ./* /sleeptery/Sleeptery-AI-DEV/
    - cd /sleeptery/Sleeptery-AI-DEV/
    # - docker compose down
    - docker compose up --build -d
    - docker ps
    - docker logs sleep_ai_app
    - docker logs consumer_prod
    - docker logs consumer_dev
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" && $CI_PIPELINE_SOURCE == "push"'