stages:
  - build


build_image_prod:
  stage: build
  tags:
    - sleep_ai
  script:
    - rsync -zvrh ./* /sleeptery/Sleeptery-AI/
    - cd /sleeptery/Sleeptery-AI/
    - docker-compose down
    - docker compose up --build -d
    - docker ps
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" && $CI_PIPELINE_SOURCE == "push"'


