version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: ${QDRANT_NAME}
    ports:
      - "${QDRANT_PORT}:6333"
    volumes:
      - ./appqdrant_storage:/qdrant/storage
    restart: always
    networks:
      - default

  redis:
    image: redis:7-alpine
    container_name: ${REDIS_NAME}
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - "${REDIS_PORT}:6379"
    restart: always
    networks:
      - default

  app:
    build: .
    container_name: ${CONTAINER_NAME}
    env_file:
      - .env
    ports:
      - "${CONTAINER_PORT}:8881"
    depends_on:
      - qdrant
    environment:
      QDRANT_HOST: qdrant
      QDRANT_PORT: ${QDRANT_PORT}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      HF_TOKEN: ${HF_TOKEN}
    restart: always
    networks:
      - default

  consumer:
    restart: always
    build: .
    container_name: ${CONSUMER_NAME}
    command: bash -c "python -m app.tasks.consumer"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - default

networks:
  default:
    external: true
    name: sleeptery